### ISSUE TITLE
about Robotpose.dat

### ISSUE THREAD

**Issue by hgtt** [Shiyu-Xing/RegHEC#3]
Hi, thanks for your work. You say ,first 3 elements in each row are Euler angles for orientation and second 3 elements are positions.So i would like to know it is [x,y,z] or [z,y,x] or it is no matter?

**Comment by Shiyu-Xing** [comment]
Hello,
They are rotation angle about x, y and z axis respectively, in radian.
Our robot follows the zyx sequence when transforming to SO(3).
Some modification might be needed to make the code compatible with your robot euler angle definition.

**Comment by hgtt** [comment]
你好，感谢你的解答!根据你的回答，我的理解是:rx就是绕着x轴转动的欧拉角，而Robotpose.dat内的六个数据顺序应该是【rx,ry,rz,x,y,z】。不知道我的理解是否正确？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shiyu-Xing/RegHEC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Shiyu-Xing/RegHEC] about Robotpose.dat (Issue #3)





 
Hello,
 They are rotation angle about x, y and z axis respectively, in radian.
 Our robot follows the zyx sequence when transforming to SO(3).
 Some modification might be needed to make the code compatible with your robot euler angle definition.

**Comment by Shiyu-Xing** [comment]
你的理解没有问题。可以参考当前版本RegHEC.cpp中line 538 到540。

**Comment by hgtt** [comment]
十分感谢您的耐心解答！这对我的帮助很大！












黄广涛
***@***.***


---Original---
From: "Shiyu ***@***.***&gt;
Date: Thu, Nov 2, 2023 10:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Shiyu-Xing/RegHEC] about Robotpose.dat (Issue #3)




 
你的理解没有问题。可以参考当前版本RegHEC.cpp中line 538 到540。
